//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace iArsenal.Entity.Arsenal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceArsenalSoap", Namespace="http://service.arsenal.cn/")]
    public partial class ServiceArsenal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMatchsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlayersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceArsenal() {
            this.Url = global::iArsenal.Entity.Properties.Settings.Default.iArsenal_Entity_Arsenal_ServiceArsenal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMatchsCompletedEventHandler GetMatchsCompleted;
        
        /// <remarks/>
        public event GetPlayersCompletedEventHandler GetPlayersCompleted;
        
        /// <remarks/>
        public event GetTeamsCompletedEventHandler GetTeamsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.arsenal.cn/GetMatchs", RequestNamespace="http://service.arsenal.cn/", ResponseNamespace="http://service.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Match[] GetMatchs() {
            object[] results = this.Invoke("GetMatchs", new object[0]);
            return ((Match[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchsAsync() {
            this.GetMatchsAsync(null);
        }
        
        /// <remarks/>
        public void GetMatchsAsync(object userState) {
            if ((this.GetMatchsOperationCompleted == null)) {
                this.GetMatchsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchsOperationCompleted);
            }
            this.InvokeAsync("GetMatchs", new object[0], this.GetMatchsOperationCompleted, userState);
        }
        
        private void OnGetMatchsOperationCompleted(object arg) {
            if ((this.GetMatchsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchsCompleted(this, new GetMatchsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.arsenal.cn/GetPlayers", RequestNamespace="http://service.arsenal.cn/", ResponseNamespace="http://service.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Player[] GetPlayers() {
            object[] results = this.Invoke("GetPlayers", new object[0]);
            return ((Player[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPlayersAsync() {
            this.GetPlayersAsync(null);
        }
        
        /// <remarks/>
        public void GetPlayersAsync(object userState) {
            if ((this.GetPlayersOperationCompleted == null)) {
                this.GetPlayersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlayersOperationCompleted);
            }
            this.InvokeAsync("GetPlayers", new object[0], this.GetPlayersOperationCompleted, userState);
        }
        
        private void OnGetPlayersOperationCompleted(object arg) {
            if ((this.GetPlayersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlayersCompleted(this, new GetPlayersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.arsenal.cn/GetTeams", RequestNamespace="http://service.arsenal.cn/", ResponseNamespace="http://service.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Team[] GetTeams() {
            object[] results = this.Invoke("GetTeams", new object[0]);
            return ((Team[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamsAsync() {
            this.GetTeamsAsync(null);
        }
        
        /// <remarks/>
        public void GetTeamsAsync(object userState) {
            if ((this.GetTeamsOperationCompleted == null)) {
                this.GetTeamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamsOperationCompleted);
            }
            this.InvokeAsync("GetTeams", new object[0], this.GetTeamsOperationCompleted, userState);
        }
        
        private void OnGetTeamsOperationCompleted(object arg) {
            if ((this.GetTeamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamsCompleted(this, new GetTeamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.arsenal.cn/")]
    public partial class Match {
        
        private System.Guid matchGuidField;
        
        private System.Guid teamGuidField;
        
        private string teamNameField;
        
        private bool isHomeField;
        
        private System.Nullable<int> resultHomeField;
        
        private System.Nullable<int> resultAwayField;
        
        private string resultInfoField;
        
        private System.DateTime playTimeField;
        
        private System.Nullable<System.Guid> leagueGuidField;
        
        private string leagueNameField;
        
        private System.Nullable<int> roundField;
        
        private System.Nullable<System.Guid> groupGuidField;
        
        private System.Nullable<System.Guid> casinoMatchGuidField;
        
        private string reportImageURLField;
        
        private string reportURLField;
        
        private string topicURLField;
        
        private bool isActiveField;
        
        private string remarkField;
        
        /// <remarks/>
        public System.Guid MatchGuid {
            get {
                return this.matchGuidField;
            }
            set {
                this.matchGuidField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid TeamGuid {
            get {
                return this.teamGuidField;
            }
            set {
                this.teamGuidField = value;
            }
        }
        
        /// <remarks/>
        public string TeamName {
            get {
                return this.teamNameField;
            }
            set {
                this.teamNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHome {
            get {
                return this.isHomeField;
            }
            set {
                this.isHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ResultHome {
            get {
                return this.resultHomeField;
            }
            set {
                this.resultHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ResultAway {
            get {
                return this.resultAwayField;
            }
            set {
                this.resultAwayField = value;
            }
        }
        
        /// <remarks/>
        public string ResultInfo {
            get {
                return this.resultInfoField;
            }
            set {
                this.resultInfoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PlayTime {
            get {
                return this.playTimeField;
            }
            set {
                this.playTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> LeagueGuid {
            get {
                return this.leagueGuidField;
            }
            set {
                this.leagueGuidField = value;
            }
        }
        
        /// <remarks/>
        public string LeagueName {
            get {
                return this.leagueNameField;
            }
            set {
                this.leagueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Round {
            get {
                return this.roundField;
            }
            set {
                this.roundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> GroupGuid {
            get {
                return this.groupGuidField;
            }
            set {
                this.groupGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> CasinoMatchGuid {
            get {
                return this.casinoMatchGuidField;
            }
            set {
                this.casinoMatchGuidField = value;
            }
        }
        
        /// <remarks/>
        public string ReportImageURL {
            get {
                return this.reportImageURLField;
            }
            set {
                this.reportImageURLField = value;
            }
        }
        
        /// <remarks/>
        public string ReportURL {
            get {
                return this.reportURLField;
            }
            set {
                this.reportURLField = value;
            }
        }
        
        /// <remarks/>
        public string TopicURL {
            get {
                return this.topicURLField;
            }
            set {
                this.topicURLField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.arsenal.cn/")]
    public partial class Team {
        
        private System.Guid teamGuidField;
        
        private string teamEnglishNameField;
        
        private string teamDisplayNameField;
        
        private string teamLogoField;
        
        private string teamNickNameField;
        
        private string foundedField;
        
        private string groundField;
        
        private System.Nullable<int> capacityField;
        
        private string chairmanField;
        
        private string managerField;
        
        private System.Guid leagueGuidField;
        
        private int leagueCountInfoField;
        
        /// <remarks/>
        public System.Guid TeamGuid {
            get {
                return this.teamGuidField;
            }
            set {
                this.teamGuidField = value;
            }
        }
        
        /// <remarks/>
        public string TeamEnglishName {
            get {
                return this.teamEnglishNameField;
            }
            set {
                this.teamEnglishNameField = value;
            }
        }
        
        /// <remarks/>
        public string TeamDisplayName {
            get {
                return this.teamDisplayNameField;
            }
            set {
                this.teamDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        public string TeamLogo {
            get {
                return this.teamLogoField;
            }
            set {
                this.teamLogoField = value;
            }
        }
        
        /// <remarks/>
        public string TeamNickName {
            get {
                return this.teamNickNameField;
            }
            set {
                this.teamNickNameField = value;
            }
        }
        
        /// <remarks/>
        public string Founded {
            get {
                return this.foundedField;
            }
            set {
                this.foundedField = value;
            }
        }
        
        /// <remarks/>
        public string Ground {
            get {
                return this.groundField;
            }
            set {
                this.groundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        public string Chairman {
            get {
                return this.chairmanField;
            }
            set {
                this.chairmanField = value;
            }
        }
        
        /// <remarks/>
        public string Manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid LeagueGuid {
            get {
                return this.leagueGuidField;
            }
            set {
                this.leagueGuidField = value;
            }
        }
        
        /// <remarks/>
        public int LeagueCountInfo {
            get {
                return this.leagueCountInfoField;
            }
            set {
                this.leagueCountInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.arsenal.cn/")]
    public partial class Player {
        
        private System.Guid playerGuidField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string displayNameField;
        
        private PlayerPosition positionField;
        
        private int squadNumberField;
        
        private string faceURLField;
        
        private string photoURLField;
        
        private int offsetField;
        
        private bool isLegendField;
        
        private bool isLoanField;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private string bornField;
        
        private int startsField;
        
        private int subsField;
        
        private int appsField;
        
        private int goalsField;
        
        private System.Nullable<System.DateTime> joinDateField;
        
        private string joinedField;
        
        private string leftField;
        
        private string debutField;
        
        private string firstGoalField;
        
        private string previousClubsField;
        
        private string profileField;
        
        /// <remarks/>
        public System.Guid PlayerGuid {
            get {
                return this.playerGuidField;
            }
            set {
                this.playerGuidField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public PlayerPosition Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public int SquadNumber {
            get {
                return this.squadNumberField;
            }
            set {
                this.squadNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FaceURL {
            get {
                return this.faceURLField;
            }
            set {
                this.faceURLField = value;
            }
        }
        
        /// <remarks/>
        public string PhotoURL {
            get {
                return this.photoURLField;
            }
            set {
                this.photoURLField = value;
            }
        }
        
        /// <remarks/>
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLegend {
            get {
                return this.isLegendField;
            }
            set {
                this.isLegendField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLoan {
            get {
                return this.isLoanField;
            }
            set {
                this.isLoanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public string Born {
            get {
                return this.bornField;
            }
            set {
                this.bornField = value;
            }
        }
        
        /// <remarks/>
        public int Starts {
            get {
                return this.startsField;
            }
            set {
                this.startsField = value;
            }
        }
        
        /// <remarks/>
        public int Subs {
            get {
                return this.subsField;
            }
            set {
                this.subsField = value;
            }
        }
        
        /// <remarks/>
        public int Apps {
            get {
                return this.appsField;
            }
            set {
                this.appsField = value;
            }
        }
        
        /// <remarks/>
        public int Goals {
            get {
                return this.goalsField;
            }
            set {
                this.goalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> JoinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        public string Joined {
            get {
                return this.joinedField;
            }
            set {
                this.joinedField = value;
            }
        }
        
        /// <remarks/>
        public string Left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        public string Debut {
            get {
                return this.debutField;
            }
            set {
                this.debutField = value;
            }
        }
        
        /// <remarks/>
        public string FirstGoal {
            get {
                return this.firstGoalField;
            }
            set {
                this.firstGoalField = value;
            }
        }
        
        /// <remarks/>
        public string PreviousClubs {
            get {
                return this.previousClubsField;
            }
            set {
                this.previousClubsField = value;
            }
        }
        
        /// <remarks/>
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.arsenal.cn/")]
    public enum PlayerPosition {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Goalkeeper,
        
        /// <remarks/>
        Defender,
        
        /// <remarks/>
        Midfielder,
        
        /// <remarks/>
        Forward,
        
        /// <remarks/>
        Coach,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetMatchsCompletedEventHandler(object sender, GetMatchsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Match[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Match[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPlayersCompletedEventHandler(object sender, GetPlayersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlayersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlayersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Player[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Player[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetTeamsCompletedEventHandler(object sender, GetTeamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Team[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Team[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591