//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Arsenalcn.ClubSys.Service.Arsenal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceArsenalSoap", Namespace="http://www.arsenal.cn/")]
    public partial class ServiceArsenal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetMatchsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlayersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamsByLeagueGuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLeaguesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVideosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceArsenal() {
            this.Url = global::Arsenalcn.ClubSys.Service.Properties.Settings.Default.Arsenalcn_ClubSys_Service_Arsenal_ServiceArsenal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetMatchsCompletedEventHandler GetMatchsCompleted;
        
        /// <remarks/>
        public event GetPlayersCompletedEventHandler GetPlayersCompleted;
        
        /// <remarks/>
        public event GetTeamsCompletedEventHandler GetTeamsCompleted;
        
        /// <remarks/>
        public event GetTeamsByLeagueGuidCompletedEventHandler GetTeamsByLeagueGuidCompleted;
        
        /// <remarks/>
        public event GetLeaguesCompletedEventHandler GetLeaguesCompleted;
        
        /// <remarks/>
        public event GetVideosCompletedEventHandler GetVideosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.arsenal.cn/GetMatchs", RequestNamespace="http://www.arsenal.cn/", ResponseNamespace="http://www.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Match[] GetMatchs() {
            object[] results = this.Invoke("GetMatchs", new object[0]);
            return ((Match[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMatchsAsync() {
            this.GetMatchsAsync(null);
        }
        
        /// <remarks/>
        public void GetMatchsAsync(object userState) {
            if ((this.GetMatchsOperationCompleted == null)) {
                this.GetMatchsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatchsOperationCompleted);
            }
            this.InvokeAsync("GetMatchs", new object[0], this.GetMatchsOperationCompleted, userState);
        }
        
        private void OnGetMatchsOperationCompleted(object arg) {
            if ((this.GetMatchsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatchsCompleted(this, new GetMatchsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.arsenal.cn/GetPlayers", RequestNamespace="http://www.arsenal.cn/", ResponseNamespace="http://www.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Player[] GetPlayers() {
            object[] results = this.Invoke("GetPlayers", new object[0]);
            return ((Player[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPlayersAsync() {
            this.GetPlayersAsync(null);
        }
        
        /// <remarks/>
        public void GetPlayersAsync(object userState) {
            if ((this.GetPlayersOperationCompleted == null)) {
                this.GetPlayersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlayersOperationCompleted);
            }
            this.InvokeAsync("GetPlayers", new object[0], this.GetPlayersOperationCompleted, userState);
        }
        
        private void OnGetPlayersOperationCompleted(object arg) {
            if ((this.GetPlayersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlayersCompleted(this, new GetPlayersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.arsenal.cn/GetTeams", RequestNamespace="http://www.arsenal.cn/", ResponseNamespace="http://www.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Team[] GetTeams() {
            object[] results = this.Invoke("GetTeams", new object[0]);
            return ((Team[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamsAsync() {
            this.GetTeamsAsync(null);
        }
        
        /// <remarks/>
        public void GetTeamsAsync(object userState) {
            if ((this.GetTeamsOperationCompleted == null)) {
                this.GetTeamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamsOperationCompleted);
            }
            this.InvokeAsync("GetTeams", new object[0], this.GetTeamsOperationCompleted, userState);
        }
        
        private void OnGetTeamsOperationCompleted(object arg) {
            if ((this.GetTeamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamsCompleted(this, new GetTeamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.arsenal.cn/GetTeamsByLeagueGuid", RequestNamespace="http://www.arsenal.cn/", ResponseNamespace="http://www.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Team[] GetTeamsByLeagueGuid(System.Guid guid) {
            object[] results = this.Invoke("GetTeamsByLeagueGuid", new object[] {
                        guid});
            return ((Team[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamsByLeagueGuidAsync(System.Guid guid) {
            this.GetTeamsByLeagueGuidAsync(guid, null);
        }
        
        /// <remarks/>
        public void GetTeamsByLeagueGuidAsync(System.Guid guid, object userState) {
            if ((this.GetTeamsByLeagueGuidOperationCompleted == null)) {
                this.GetTeamsByLeagueGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamsByLeagueGuidOperationCompleted);
            }
            this.InvokeAsync("GetTeamsByLeagueGuid", new object[] {
                        guid}, this.GetTeamsByLeagueGuidOperationCompleted, userState);
        }
        
        private void OnGetTeamsByLeagueGuidOperationCompleted(object arg) {
            if ((this.GetTeamsByLeagueGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamsByLeagueGuidCompleted(this, new GetTeamsByLeagueGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.arsenal.cn/GetLeagues", RequestNamespace="http://www.arsenal.cn/", ResponseNamespace="http://www.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public League[] GetLeagues() {
            object[] results = this.Invoke("GetLeagues", new object[0]);
            return ((League[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLeaguesAsync() {
            this.GetLeaguesAsync(null);
        }
        
        /// <remarks/>
        public void GetLeaguesAsync(object userState) {
            if ((this.GetLeaguesOperationCompleted == null)) {
                this.GetLeaguesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLeaguesOperationCompleted);
            }
            this.InvokeAsync("GetLeagues", new object[0], this.GetLeaguesOperationCompleted, userState);
        }
        
        private void OnGetLeaguesOperationCompleted(object arg) {
            if ((this.GetLeaguesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLeaguesCompleted(this, new GetLeaguesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.arsenal.cn/GetVideos", RequestNamespace="http://www.arsenal.cn/", ResponseNamespace="http://www.arsenal.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Video[] GetVideos() {
            object[] results = this.Invoke("GetVideos", new object[0]);
            return ((Video[])(results[0]));
        }
        
        /// <remarks/>
        public void GetVideosAsync() {
            this.GetVideosAsync(null);
        }
        
        /// <remarks/>
        public void GetVideosAsync(object userState) {
            if ((this.GetVideosOperationCompleted == null)) {
                this.GetVideosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVideosOperationCompleted);
            }
            this.InvokeAsync("GetVideos", new object[0], this.GetVideosOperationCompleted, userState);
        }
        
        private void OnGetVideosOperationCompleted(object arg) {
            if ((this.GetVideosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVideosCompleted(this, new GetVideosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arsenal.cn/")]
    public partial class Match {
        
        private System.Guid matchGuidField;
        
        private System.Guid teamGuidField;
        
        private string teamNameField;
        
        private bool isHomeField;
        
        private System.Nullable<int> resultHomeField;
        
        private System.Nullable<int> resultAwayField;
        
        private string resultInfoField;
        
        private System.DateTime playTimeField;
        
        private System.Nullable<System.Guid> leagueGuidField;
        
        private string leagueNameField;
        
        private System.Nullable<int> roundField;
        
        private System.Nullable<System.Guid> groupGuidField;
        
        private System.Nullable<System.Guid> casinoMatchGuidField;
        
        private string reportImageURLField;
        
        private string reportURLField;
        
        private string topicURLField;
        
        private bool isActiveField;
        
        private string remarkField;
        
        /// <remarks/>
        public System.Guid MatchGuid {
            get {
                return this.matchGuidField;
            }
            set {
                this.matchGuidField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid TeamGuid {
            get {
                return this.teamGuidField;
            }
            set {
                this.teamGuidField = value;
            }
        }
        
        /// <remarks/>
        public string TeamName {
            get {
                return this.teamNameField;
            }
            set {
                this.teamNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsHome {
            get {
                return this.isHomeField;
            }
            set {
                this.isHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ResultHome {
            get {
                return this.resultHomeField;
            }
            set {
                this.resultHomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ResultAway {
            get {
                return this.resultAwayField;
            }
            set {
                this.resultAwayField = value;
            }
        }
        
        /// <remarks/>
        public string ResultInfo {
            get {
                return this.resultInfoField;
            }
            set {
                this.resultInfoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PlayTime {
            get {
                return this.playTimeField;
            }
            set {
                this.playTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> LeagueGuid {
            get {
                return this.leagueGuidField;
            }
            set {
                this.leagueGuidField = value;
            }
        }
        
        /// <remarks/>
        public string LeagueName {
            get {
                return this.leagueNameField;
            }
            set {
                this.leagueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Round {
            get {
                return this.roundField;
            }
            set {
                this.roundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> GroupGuid {
            get {
                return this.groupGuidField;
            }
            set {
                this.groupGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> CasinoMatchGuid {
            get {
                return this.casinoMatchGuidField;
            }
            set {
                this.casinoMatchGuidField = value;
            }
        }
        
        /// <remarks/>
        public string ReportImageURL {
            get {
                return this.reportImageURLField;
            }
            set {
                this.reportImageURLField = value;
            }
        }
        
        /// <remarks/>
        public string ReportURL {
            get {
                return this.reportURLField;
            }
            set {
                this.reportURLField = value;
            }
        }
        
        /// <remarks/>
        public string TopicURL {
            get {
                return this.topicURLField;
            }
            set {
                this.topicURLField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arsenal.cn/")]
    public partial class Video {
        
        private System.Guid videoGuidField;
        
        private string fileNameField;
        
        private System.Nullable<System.Guid> arsenalMatchGuidField;
        
        private System.Nullable<System.Guid> goalPlayerGuidField;
        
        private string goalPlayerNameField;
        
        private System.Nullable<System.Guid> assistPlayerGuidField;
        
        private string assistPlayerNameField;
        
        private string goalRankField;
        
        private string teamworkRankField;
        
        private VideoFileType videoTypeField;
        
        private int videoLengthField;
        
        private int videoWidthField;
        
        private int videoHeightField;
        
        private string goalYearField;
        
        private string opponentField;
        
        private string videoFilePathField;
        
        /// <remarks/>
        public System.Guid VideoGuid {
            get {
                return this.videoGuidField;
            }
            set {
                this.videoGuidField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> ArsenalMatchGuid {
            get {
                return this.arsenalMatchGuidField;
            }
            set {
                this.arsenalMatchGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> GoalPlayerGuid {
            get {
                return this.goalPlayerGuidField;
            }
            set {
                this.goalPlayerGuidField = value;
            }
        }
        
        /// <remarks/>
        public string GoalPlayerName {
            get {
                return this.goalPlayerNameField;
            }
            set {
                this.goalPlayerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> AssistPlayerGuid {
            get {
                return this.assistPlayerGuidField;
            }
            set {
                this.assistPlayerGuidField = value;
            }
        }
        
        /// <remarks/>
        public string AssistPlayerName {
            get {
                return this.assistPlayerNameField;
            }
            set {
                this.assistPlayerNameField = value;
            }
        }
        
        /// <remarks/>
        public string GoalRank {
            get {
                return this.goalRankField;
            }
            set {
                this.goalRankField = value;
            }
        }
        
        /// <remarks/>
        public string TeamworkRank {
            get {
                return this.teamworkRankField;
            }
            set {
                this.teamworkRankField = value;
            }
        }
        
        /// <remarks/>
        public VideoFileType VideoType {
            get {
                return this.videoTypeField;
            }
            set {
                this.videoTypeField = value;
            }
        }
        
        /// <remarks/>
        public int VideoLength {
            get {
                return this.videoLengthField;
            }
            set {
                this.videoLengthField = value;
            }
        }
        
        /// <remarks/>
        public int VideoWidth {
            get {
                return this.videoWidthField;
            }
            set {
                this.videoWidthField = value;
            }
        }
        
        /// <remarks/>
        public int VideoHeight {
            get {
                return this.videoHeightField;
            }
            set {
                this.videoHeightField = value;
            }
        }
        
        /// <remarks/>
        public string GoalYear {
            get {
                return this.goalYearField;
            }
            set {
                this.goalYearField = value;
            }
        }
        
        /// <remarks/>
        public string Opponent {
            get {
                return this.opponentField;
            }
            set {
                this.opponentField = value;
            }
        }
        
        /// <remarks/>
        public string VideoFilePath {
            get {
                return this.videoFilePathField;
            }
            set {
                this.videoFilePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arsenal.cn/")]
    public enum VideoFileType {
        
        /// <remarks/>
        flv,
        
        /// <remarks/>
        mp4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arsenal.cn/")]
    public partial class League {
        
        private System.Guid leagueGuidField;
        
        private string leagueNameField;
        
        private string leagueOrgNameField;
        
        private string leagueSeasonField;
        
        private System.DateTime leagueTimeField;
        
        private string leagueLogoField;
        
        private int leagueOrderField;
        
        private bool isActiveField;
        
        private int teamCountInfoField;
        
        private string leagueNameInfoField;
        
        /// <remarks/>
        public System.Guid LeagueGuid {
            get {
                return this.leagueGuidField;
            }
            set {
                this.leagueGuidField = value;
            }
        }
        
        /// <remarks/>
        public string LeagueName {
            get {
                return this.leagueNameField;
            }
            set {
                this.leagueNameField = value;
            }
        }
        
        /// <remarks/>
        public string LeagueOrgName {
            get {
                return this.leagueOrgNameField;
            }
            set {
                this.leagueOrgNameField = value;
            }
        }
        
        /// <remarks/>
        public string LeagueSeason {
            get {
                return this.leagueSeasonField;
            }
            set {
                this.leagueSeasonField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LeagueTime {
            get {
                return this.leagueTimeField;
            }
            set {
                this.leagueTimeField = value;
            }
        }
        
        /// <remarks/>
        public string LeagueLogo {
            get {
                return this.leagueLogoField;
            }
            set {
                this.leagueLogoField = value;
            }
        }
        
        /// <remarks/>
        public int LeagueOrder {
            get {
                return this.leagueOrderField;
            }
            set {
                this.leagueOrderField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public int TeamCountInfo {
            get {
                return this.teamCountInfoField;
            }
            set {
                this.teamCountInfoField = value;
            }
        }
        
        /// <remarks/>
        public string LeagueNameInfo {
            get {
                return this.leagueNameInfoField;
            }
            set {
                this.leagueNameInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arsenal.cn/")]
    public partial class Team {
        
        private System.Guid teamGuidField;
        
        private string teamEnglishNameField;
        
        private string teamDisplayNameField;
        
        private string teamLogoField;
        
        private string teamNickNameField;
        
        private string foundedField;
        
        private string groundField;
        
        private System.Nullable<int> capacityField;
        
        private string chairmanField;
        
        private string managerField;
        
        private System.Guid leagueGuidField;
        
        private int leagueCountInfoField;
        
        /// <remarks/>
        public System.Guid TeamGuid {
            get {
                return this.teamGuidField;
            }
            set {
                this.teamGuidField = value;
            }
        }
        
        /// <remarks/>
        public string TeamEnglishName {
            get {
                return this.teamEnglishNameField;
            }
            set {
                this.teamEnglishNameField = value;
            }
        }
        
        /// <remarks/>
        public string TeamDisplayName {
            get {
                return this.teamDisplayNameField;
            }
            set {
                this.teamDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        public string TeamLogo {
            get {
                return this.teamLogoField;
            }
            set {
                this.teamLogoField = value;
            }
        }
        
        /// <remarks/>
        public string TeamNickName {
            get {
                return this.teamNickNameField;
            }
            set {
                this.teamNickNameField = value;
            }
        }
        
        /// <remarks/>
        public string Founded {
            get {
                return this.foundedField;
            }
            set {
                this.foundedField = value;
            }
        }
        
        /// <remarks/>
        public string Ground {
            get {
                return this.groundField;
            }
            set {
                this.groundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        public string Chairman {
            get {
                return this.chairmanField;
            }
            set {
                this.chairmanField = value;
            }
        }
        
        /// <remarks/>
        public string Manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid LeagueGuid {
            get {
                return this.leagueGuidField;
            }
            set {
                this.leagueGuidField = value;
            }
        }
        
        /// <remarks/>
        public int LeagueCountInfo {
            get {
                return this.leagueCountInfoField;
            }
            set {
                this.leagueCountInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arsenal.cn/")]
    public partial class Player {
        
        private System.Guid playerGuidField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string displayNameField;
        
        private string printingNameField;
        
        private PlayerPostionType positionField;
        
        private int squadNumberField;
        
        private string faceURLField;
        
        private string photoURLField;
        
        private int offsetField;
        
        private bool isLegendField;
        
        private bool isLoanField;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private string bornField;
        
        private int startsField;
        
        private int subsField;
        
        private int appsField;
        
        private int goalsField;
        
        private System.Nullable<System.DateTime> joinDateField;
        
        private string joinedField;
        
        private string leftField;
        
        private string debutField;
        
        private string firstGoalField;
        
        private string previousClubsField;
        
        private string profileField;
        
        /// <remarks/>
        public System.Guid PlayerGuid {
            get {
                return this.playerGuidField;
            }
            set {
                this.playerGuidField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        public string PrintingName {
            get {
                return this.printingNameField;
            }
            set {
                this.printingNameField = value;
            }
        }
        
        /// <remarks/>
        public PlayerPostionType Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public int SquadNumber {
            get {
                return this.squadNumberField;
            }
            set {
                this.squadNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FaceURL {
            get {
                return this.faceURLField;
            }
            set {
                this.faceURLField = value;
            }
        }
        
        /// <remarks/>
        public string PhotoURL {
            get {
                return this.photoURLField;
            }
            set {
                this.photoURLField = value;
            }
        }
        
        /// <remarks/>
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLegend {
            get {
                return this.isLegendField;
            }
            set {
                this.isLegendField = value;
            }
        }
        
        /// <remarks/>
        public bool IsLoan {
            get {
                return this.isLoanField;
            }
            set {
                this.isLoanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        public string Born {
            get {
                return this.bornField;
            }
            set {
                this.bornField = value;
            }
        }
        
        /// <remarks/>
        public int Starts {
            get {
                return this.startsField;
            }
            set {
                this.startsField = value;
            }
        }
        
        /// <remarks/>
        public int Subs {
            get {
                return this.subsField;
            }
            set {
                this.subsField = value;
            }
        }
        
        /// <remarks/>
        public int Apps {
            get {
                return this.appsField;
            }
            set {
                this.appsField = value;
            }
        }
        
        /// <remarks/>
        public int Goals {
            get {
                return this.goalsField;
            }
            set {
                this.goalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> JoinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        public string Joined {
            get {
                return this.joinedField;
            }
            set {
                this.joinedField = value;
            }
        }
        
        /// <remarks/>
        public string Left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        public string Debut {
            get {
                return this.debutField;
            }
            set {
                this.debutField = value;
            }
        }
        
        /// <remarks/>
        public string FirstGoal {
            get {
                return this.firstGoalField;
            }
            set {
                this.firstGoalField = value;
            }
        }
        
        /// <remarks/>
        public string PreviousClubs {
            get {
                return this.previousClubsField;
            }
            set {
                this.previousClubsField = value;
            }
        }
        
        /// <remarks/>
        public string Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arsenal.cn/")]
    public enum PlayerPostionType {
        
        /// <remarks/>
        Null,
        
        /// <remarks/>
        Goalkeeper,
        
        /// <remarks/>
        Defender,
        
        /// <remarks/>
        Midfielder,
        
        /// <remarks/>
        Forward,
        
        /// <remarks/>
        Coach,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMatchsCompletedEventHandler(object sender, GetMatchsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatchsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatchsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Match[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Match[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPlayersCompletedEventHandler(object sender, GetPlayersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlayersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlayersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Player[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Player[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTeamsCompletedEventHandler(object sender, GetTeamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Team[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Team[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTeamsByLeagueGuidCompletedEventHandler(object sender, GetTeamsByLeagueGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamsByLeagueGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamsByLeagueGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Team[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Team[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetLeaguesCompletedEventHandler(object sender, GetLeaguesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLeaguesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLeaguesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public League[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((League[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetVideosCompletedEventHandler(object sender, GetVideosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVideosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVideosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Video[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Video[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591