//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arsenalcn.ClubSys.Web {
    
    
    public partial class ClubStrip {
        
        /// <summary>
        /// ctrlLeftPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Arsenalcn.ClubSys.Web.Control.LeftPanel ctrlLeftPanel;
        
        /// <summary>
        /// ctrlFieldToolBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Arsenalcn.ClubSys.Web.Control.FieldToolBar ctrlFieldToolBar;
        
        /// <summary>
        /// ctrlMenuTabBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Arsenalcn.ClubSys.Web.Control.MenuTabBar ctrlMenuTabBar;
        
        /// <summary>
        /// ctrlClubSysHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Arsenalcn.ClubSys.Web.Control.ClubSysHeader ctrlClubSysHeader;
        
        /// <summary>
        /// ltlClubBingoStrip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltlClubBingoStrip;
        
        /// <summary>
        /// ltlClubStripCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltlClubStripCount;
        
        /// <summary>
        /// gvClubStrip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvClubStrip;
    }
}
