//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arsenalcn.Framework.DataAccess.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account : Entity
    {
        public Account()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
